name: Build GUI exe with Pyinstaller

on:
  push:
    tags:
    - 'release-v*'

jobs:
  release:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: ./

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "dist/app"
        token: ${{ secrets.GITHUB_TOKEN }}


