# This is a basic workflow to help you get started with Actions

name: Release Application

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version  (ie 5.5.0)'
        required: true
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:      
      - uses: actions/checkout@v2
      
      - name: Package Windows Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: ./

      - name: Package Linux Application
        uses: JackMcKew/pyinstaller-action-linux@0.1.4
        with:
          path: ./
          tkinter: true
      
      - name: List All Files
        run: |
          ls dist/windows
          ls dist/linux

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/linux/app/*"
          name: Google Translate v${{ github.event.inputs.versionName }}
          tag: v${{ github.event.inputs.versionName }}
          token: ${{ secrets.GITHUB_TOKEN }}


#       - name: Upload Artifact
#         uses: actions/upload-artifact@v2
#         with:
#           name: ${{ matrix.os }}
#           path: dist/*

#   release:
#     # The type of runner that the job will run on
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Download ubuntu-latest Artrifact
#         uses: actions/download-artifact@v2
#         with:
#           name: ubuntu-latest
#           path: GoogleTranslator-v${{ github.event.inputs.versionName }}-linux
      
#       - name: Download windows-latest Artrifact
#         uses: actions/download-artifact@v2
#         with:
#           name: windows-latest
#           path: GoogleTranslator-v${{ github.event.inputs.versionName }}-win
          
#       - name: List All Files
#         run: ls .

# - uses: ncipollo/release-action@v1
#         with:
#           artifacts: "dist/linux/app"
#           name: Google Translate v${{ github.event.inputs.versionName }}
#           tag: v${{ github.event.inputs.versionName }}
#           token: ${{ secrets.GITHUB_TOKEN }}
